"""Add User model and operator_id, qa_signoff to ProductionOrder

Revision ID: 6c8a26c9c62e
Revises: 7d94cf32c909
Create Date: 2025-03-04 22:34:56.189362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c8a26c9c62e'
down_revision = '7d94cf32c909'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('production_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('operator_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('qa_signoff', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['operator_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('qa_signoff')
        batch_op.drop_column('operator_id')

    op.drop_table('user')
    # ### end Alembic commands ###
