"""Add notes to ProductionOrder

Revision ID: 7d94cf32c909
Revises: f847aa416be8
Create Date: 2025-03-04 22:22:40.462871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d94cf32c909'
down_revision = 'f847aa416be8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_order', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
