"""Add batch_number and expiry_date to inventory

Revision ID: ca255bd8e6de
Revises: <new_hash>
Create Date: 2025-03-04 18:51:31.815080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca255bd8e6de'
down_revision = '<new_hash>'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('expiry_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_column('expiry_date')
        batch_op.drop_column('batch_number')

    # ### end Alembic commands ###
