"""Add notes and instructions to Product

Revision ID: ce1f8081d25e
Revises: ca255bd8e6de
Create Date: 2025-03-04 19:57:13.711713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce1f8081d25e'
down_revision = 'ca255bd8e6de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('instructions', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('instructions')
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
