"""Add date_submitted to ProductionOrder

Revision ID: d4ef1790e37e
Revises: ce1f8081d25e
Create Date: 2025-03-04 21:41:57.381396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4ef1790e37e'
down_revision = 'ce1f8081d25e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_submitted', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_order', schema=None) as batch_op:
        batch_op.drop_column('date_submitted')

    # ### end Alembic commands ###
